export default {
	extends: ["@commitlint/config-conventional"],
	rules: {
		"header-max-length": [2, "always", 72],
		"body-empty": [2, "always"],
		"scope-enum": [
			2,
			"always",
			[
				"web",
				"gateway",
				"orchestrator",
				"signer",
				"provisioner",
				"daemon",
				"bots",
				"core",
				"runtime",
				"rules",
				"db",
				"solana",
				"wallet",
				"contracts",
				"env",
				"telemetry",
				"sdk",
				"ui",
				"config",
				"testing",
				"deps",
				"ci",
				"docker",
				"repo",
				"release",
			],
		],
	},
};
