/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as GetAWalletRouteImport } from './routes/get-a-wallet'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as NewRouteImport } from './routes/new'
import { Route as PapersRouteImport } from './routes/papers'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ProfitRouteImport } from './routes/profit'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SwapRouteImport } from './routes/swap'
import { Route as TradesRouteImport } from './routes/trades'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as MMachineIdRouteImport } from './routes/m.$machineId'
import { Route as MachinesIndexRouteImport } from './routes/machines.index'
import { Route as MachinesMachineIdRouteImport } from './routes/machines.$machineId'
import { Route as MarketSolRouteImport } from './routes/market.sol'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as MarketplaceListingIdRouteImport } from './routes/marketplace.$listingId'
import { Route as NetworkIndexRouteImport } from './routes/network.index'
import { Route as NetworkNodeIdRouteImport } from './routes/network.$nodeId'
import { Route as NetworkJoinRouteImport } from './routes/network.join'
import { Route as NewsStoryIdRouteImport } from './routes/news.$storyId'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsAlertsRouteImport } from './routes/settings.alerts'
import { Route as SettingsKeysRouteImport } from './routes/settings.keys'
import { Route as TeamsIndexRouteImport } from './routes/teams.index'
import { Route as TeamsTeamIdRouteImport } from './routes/teams.$teamId'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as WalletIndexRouteImport } from './routes/wallet.index'
import { Route as WalletStakeRouteImport } from './routes/wallet.stake'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const GetAWalletRoute = GetAWalletRouteImport.update({
  id: '/get-a-wallet',
  path: '/get-a-wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersRoute = PapersRouteImport.update({
  id: '/papers',
  path: '/papers',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfitRoute = ProfitRouteImport.update({
  id: '/profit',
  path: '/profit',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapRoute = SwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesRoute = TradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const MMachineIdRoute = MMachineIdRouteImport.update({
  id: '/m/$machineId',
  path: '/m/$machineId',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesIndexRoute = MachinesIndexRouteImport.update({
  id: '/machines/',
  path: '/machines/',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesMachineIdRoute = MachinesMachineIdRouteImport.update({
  id: '/machines/$machineId',
  path: '/machines/$machineId',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketSolRoute = MarketSolRouteImport.update({
  id: '/market/sol',
  path: '/market/sol',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceListingIdRoute = MarketplaceListingIdRouteImport.update({
  id: '/marketplace/$listingId',
  path: '/marketplace/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkIndexRoute = NetworkIndexRouteImport.update({
  id: '/network/',
  path: '/network/',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkNodeIdRoute = NetworkNodeIdRouteImport.update({
  id: '/network/$nodeId',
  path: '/network/$nodeId',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkJoinRoute = NetworkJoinRouteImport.update({
  id: '/network/join',
  path: '/network/join',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsStoryIdRoute = NewsStoryIdRouteImport.update({
  id: '/news/$storyId',
  path: '/news/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAlertsRoute = SettingsAlertsRouteImport.update({
  id: '/settings/alerts',
  path: '/settings/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsKeysRoute = SettingsKeysRouteImport.update({
  id: '/settings/keys',
  path: '/settings/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletIndexRoute = WalletIndexRouteImport.update({
  id: '/wallet/',
  path: '/wallet/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletStakeRoute = WalletStakeRouteImport.update({
  id: '/wallet/stake',
  path: '/wallet/stake',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/decisions': typeof DecisionsRoute
  '/feed': typeof FeedRoute
  '/feedback': typeof FeedbackRoute
  '/fleet': typeof FleetRoute
  '/get-a-wallet': typeof GetAWalletRoute
  '/insights': typeof InsightsRoute
  '/invite': typeof InviteRoute
  '/maintenance': typeof MaintenanceRoute
  '/manager': typeof ManagerRoute
  '/new': typeof NewRoute
  '/papers': typeof PapersRoute
  '/portfolio': typeof PortfolioRoute
  '/profit': typeof ProfitRoute
  '/sign-in': typeof SignInRoute
  '/swap': typeof SwapRoute
  '/trades': typeof TradesRoute
  '/vault': typeof VaultRoute
  '/welcome': typeof WelcomeRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/m/$machineId': typeof MMachineIdRoute
  '/machines/$machineId': typeof MachinesMachineIdRoute
  '/market/sol': typeof MarketSolRoute
  '/marketplace/$listingId': typeof MarketplaceListingIdRoute
  '/network/$nodeId': typeof NetworkNodeIdRoute
  '/network/join': typeof NetworkJoinRoute
  '/news/$storyId': typeof NewsStoryIdRoute
  '/settings/alerts': typeof SettingsAlertsRoute
  '/settings/keys': typeof SettingsKeysRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/u/$handle': typeof UHandleRoute
  '/wallet/stake': typeof WalletStakeRoute
  '/machines/': typeof MachinesIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/network/': typeof NetworkIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/wallet/': typeof WalletIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/decisions': typeof DecisionsRoute
  '/feed': typeof FeedRoute
  '/feedback': typeof FeedbackRoute
  '/fleet': typeof FleetRoute
  '/get-a-wallet': typeof GetAWalletRoute
  '/insights': typeof InsightsRoute
  '/invite': typeof InviteRoute
  '/maintenance': typeof MaintenanceRoute
  '/manager': typeof ManagerRoute
  '/new': typeof NewRoute
  '/papers': typeof PapersRoute
  '/portfolio': typeof PortfolioRoute
  '/profit': typeof ProfitRoute
  '/sign-in': typeof SignInRoute
  '/swap': typeof SwapRoute
  '/trades': typeof TradesRoute
  '/vault': typeof VaultRoute
  '/welcome': typeof WelcomeRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/m/$machineId': typeof MMachineIdRoute
  '/machines/$machineId': typeof MachinesMachineIdRoute
  '/market/sol': typeof MarketSolRoute
  '/marketplace/$listingId': typeof MarketplaceListingIdRoute
  '/network/$nodeId': typeof NetworkNodeIdRoute
  '/network/join': typeof NetworkJoinRoute
  '/news/$storyId': typeof NewsStoryIdRoute
  '/settings/alerts': typeof SettingsAlertsRoute
  '/settings/keys': typeof SettingsKeysRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/u/$handle': typeof UHandleRoute
  '/wallet/stake': typeof WalletStakeRoute
  '/machines': typeof MachinesIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/network': typeof NetworkIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/wallet': typeof WalletIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/decisions': typeof DecisionsRoute
  '/feed': typeof FeedRoute
  '/feedback': typeof FeedbackRoute
  '/fleet': typeof FleetRoute
  '/get-a-wallet': typeof GetAWalletRoute
  '/insights': typeof InsightsRoute
  '/invite': typeof InviteRoute
  '/maintenance': typeof MaintenanceRoute
  '/manager': typeof ManagerRoute
  '/new': typeof NewRoute
  '/papers': typeof PapersRoute
  '/portfolio': typeof PortfolioRoute
  '/profit': typeof ProfitRoute
  '/sign-in': typeof SignInRoute
  '/swap': typeof SwapRoute
  '/trades': typeof TradesRoute
  '/vault': typeof VaultRoute
  '/welcome': typeof WelcomeRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/m/$machineId': typeof MMachineIdRoute
  '/machines/$machineId': typeof MachinesMachineIdRoute
  '/market/sol': typeof MarketSolRoute
  '/marketplace/$listingId': typeof MarketplaceListingIdRoute
  '/network/$nodeId': typeof NetworkNodeIdRoute
  '/network/join': typeof NetworkJoinRoute
  '/news/$storyId': typeof NewsStoryIdRoute
  '/settings/alerts': typeof SettingsAlertsRoute
  '/settings/keys': typeof SettingsKeysRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/u/$handle': typeof UHandleRoute
  '/wallet/stake': typeof WalletStakeRoute
  '/machines/': typeof MachinesIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/network/': typeof NetworkIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/wallet/': typeof WalletIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/decisions'
    | '/feed'
    | '/feedback'
    | '/fleet'
    | '/get-a-wallet'
    | '/insights'
    | '/invite'
    | '/maintenance'
    | '/manager'
    | '/new'
    | '/papers'
    | '/portfolio'
    | '/profit'
    | '/sign-in'
    | '/swap'
    | '/trades'
    | '/vault'
    | '/welcome'
    | '/legal/privacy'
    | '/legal/terms'
    | '/m/$machineId'
    | '/machines/$machineId'
    | '/market/sol'
    | '/marketplace/$listingId'
    | '/network/$nodeId'
    | '/network/join'
    | '/news/$storyId'
    | '/settings/alerts'
    | '/settings/keys'
    | '/teams/$teamId'
    | '/u/$handle'
    | '/wallet/stake'
    | '/machines/'
    | '/marketplace/'
    | '/network/'
    | '/settings/'
    | '/teams/'
    | '/wallet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/decisions'
    | '/feed'
    | '/feedback'
    | '/fleet'
    | '/get-a-wallet'
    | '/insights'
    | '/invite'
    | '/maintenance'
    | '/manager'
    | '/new'
    | '/papers'
    | '/portfolio'
    | '/profit'
    | '/sign-in'
    | '/swap'
    | '/trades'
    | '/vault'
    | '/welcome'
    | '/legal/privacy'
    | '/legal/terms'
    | '/m/$machineId'
    | '/machines/$machineId'
    | '/market/sol'
    | '/marketplace/$listingId'
    | '/network/$nodeId'
    | '/network/join'
    | '/news/$storyId'
    | '/settings/alerts'
    | '/settings/keys'
    | '/teams/$teamId'
    | '/u/$handle'
    | '/wallet/stake'
    | '/machines'
    | '/marketplace'
    | '/network'
    | '/settings'
    | '/teams'
    | '/wallet'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/decisions'
    | '/feed'
    | '/feedback'
    | '/fleet'
    | '/get-a-wallet'
    | '/insights'
    | '/invite'
    | '/maintenance'
    | '/manager'
    | '/new'
    | '/papers'
    | '/portfolio'
    | '/profit'
    | '/sign-in'
    | '/swap'
    | '/trades'
    | '/vault'
    | '/welcome'
    | '/legal/privacy'
    | '/legal/terms'
    | '/m/$machineId'
    | '/machines/$machineId'
    | '/market/sol'
    | '/marketplace/$listingId'
    | '/network/$nodeId'
    | '/network/join'
    | '/news/$storyId'
    | '/settings/alerts'
    | '/settings/keys'
    | '/teams/$teamId'
    | '/u/$handle'
    | '/wallet/stake'
    | '/machines/'
    | '/marketplace/'
    | '/network/'
    | '/settings/'
    | '/teams/'
    | '/wallet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  DecisionsRoute: typeof DecisionsRoute
  FeedRoute: typeof FeedRoute
  FeedbackRoute: typeof FeedbackRoute
  FleetRoute: typeof FleetRoute
  GetAWalletRoute: typeof GetAWalletRoute
  InsightsRoute: typeof InsightsRoute
  InviteRoute: typeof InviteRoute
  MaintenanceRoute: typeof MaintenanceRoute
  ManagerRoute: typeof ManagerRoute
  NewRoute: typeof NewRoute
  PapersRoute: typeof PapersRoute
  PortfolioRoute: typeof PortfolioRoute
  ProfitRoute: typeof ProfitRoute
  SignInRoute: typeof SignInRoute
  SwapRoute: typeof SwapRoute
  TradesRoute: typeof TradesRoute
  VaultRoute: typeof VaultRoute
  WelcomeRoute: typeof WelcomeRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  MMachineIdRoute: typeof MMachineIdRoute
  MachinesMachineIdRoute: typeof MachinesMachineIdRoute
  MarketSolRoute: typeof MarketSolRoute
  MarketplaceListingIdRoute: typeof MarketplaceListingIdRoute
  NetworkNodeIdRoute: typeof NetworkNodeIdRoute
  NetworkJoinRoute: typeof NetworkJoinRoute
  NewsStoryIdRoute: typeof NewsStoryIdRoute
  SettingsAlertsRoute: typeof SettingsAlertsRoute
  SettingsKeysRoute: typeof SettingsKeysRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
  UHandleRoute: typeof UHandleRoute
  WalletStakeRoute: typeof WalletStakeRoute
  MachinesIndexRoute: typeof MachinesIndexRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  NetworkIndexRoute: typeof NetworkIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
  WalletIndexRoute: typeof WalletIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-a-wallet': {
      id: '/get-a-wallet'
      path: '/get-a-wallet'
      fullPath: '/get-a-wallet'
      preLoaderRoute: typeof GetAWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers': {
      id: '/papers'
      path: '/papers'
      fullPath: '/papers'
      preLoaderRoute: typeof PapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profit': {
      id: '/profit'
      path: '/profit'
      fullPath: '/profit'
      preLoaderRoute: typeof ProfitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swap': {
      id: '/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades': {
      id: '/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof TradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$machineId': {
      id: '/m/$machineId'
      path: '/m/$machineId'
      fullPath: '/m/$machineId'
      preLoaderRoute: typeof MMachineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines/': {
      id: '/machines/'
      path: '/machines'
      fullPath: '/machines/'
      preLoaderRoute: typeof MachinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines/$machineId': {
      id: '/machines/$machineId'
      path: '/machines/$machineId'
      fullPath: '/machines/$machineId'
      preLoaderRoute: typeof MachinesMachineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/sol': {
      id: '/market/sol'
      path: '/market/sol'
      fullPath: '/market/sol'
      preLoaderRoute: typeof MarketSolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$listingId': {
      id: '/marketplace/$listingId'
      path: '/marketplace/$listingId'
      fullPath: '/marketplace/$listingId'
      preLoaderRoute: typeof MarketplaceListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network/': {
      id: '/network/'
      path: '/network'
      fullPath: '/network/'
      preLoaderRoute: typeof NetworkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network/$nodeId': {
      id: '/network/$nodeId'
      path: '/network/$nodeId'
      fullPath: '/network/$nodeId'
      preLoaderRoute: typeof NetworkNodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network/join': {
      id: '/network/join'
      path: '/network/join'
      fullPath: '/network/join'
      preLoaderRoute: typeof NetworkJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$storyId': {
      id: '/news/$storyId'
      path: '/news/$storyId'
      fullPath: '/news/$storyId'
      preLoaderRoute: typeof NewsStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/alerts': {
      id: '/settings/alerts'
      path: '/settings/alerts'
      fullPath: '/settings/alerts'
      preLoaderRoute: typeof SettingsAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/keys': {
      id: '/settings/keys'
      path: '/settings/keys'
      fullPath: '/settings/keys'
      preLoaderRoute: typeof SettingsKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/': {
      id: '/wallet/'
      path: '/wallet'
      fullPath: '/wallet/'
      preLoaderRoute: typeof WalletIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/stake': {
      id: '/wallet/stake'
      path: '/wallet/stake'
      fullPath: '/wallet/stake'
      preLoaderRoute: typeof WalletStakeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  DecisionsRoute: DecisionsRoute,
  FeedRoute: FeedRoute,
  FeedbackRoute: FeedbackRoute,
  FleetRoute: FleetRoute,
  GetAWalletRoute: GetAWalletRoute,
  InsightsRoute: InsightsRoute,
  InviteRoute: InviteRoute,
  MaintenanceRoute: MaintenanceRoute,
  ManagerRoute: ManagerRoute,
  NewRoute: NewRoute,
  PapersRoute: PapersRoute,
  PortfolioRoute: PortfolioRoute,
  ProfitRoute: ProfitRoute,
  SignInRoute: SignInRoute,
  SwapRoute: SwapRoute,
  TradesRoute: TradesRoute,
  VaultRoute: VaultRoute,
  WelcomeRoute: WelcomeRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  MMachineIdRoute: MMachineIdRoute,
  MachinesMachineIdRoute: MachinesMachineIdRoute,
  MarketSolRoute: MarketSolRoute,
  MarketplaceListingIdRoute: MarketplaceListingIdRoute,
  NetworkNodeIdRoute: NetworkNodeIdRoute,
  NetworkJoinRoute: NetworkJoinRoute,
  NewsStoryIdRoute: NewsStoryIdRoute,
  SettingsAlertsRoute: SettingsAlertsRoute,
  SettingsKeysRoute: SettingsKeysRoute,
  TeamsTeamIdRoute: TeamsTeamIdRoute,
  UHandleRoute: UHandleRoute,
  WalletStakeRoute: WalletStakeRoute,
  MachinesIndexRoute: MachinesIndexRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  NetworkIndexRoute: NetworkIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
  WalletIndexRoute: WalletIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
